import Head from "next/head";
import axios from "axios";
import Featured from "../components/featured";
import PizzaList from "../components/pizzalist";
import styles from "../styles/Home.module.css";
import Locations from "../components/locations";

export default function Home({ pizzaList }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunger | Order Pizza Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Featured />
      <PizzaList pizzaList={pizzaList} />
      <Locations/>
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get("http://localhost:3000/api/products");
  return {
    props: {
      pizzaList: res.data,
    },
  };
};
